require("fqs.plugins-setup")
require("fqs.core.options")
require("fqs.core.keymaps")
require("fqs.core.colorscheme")
require("fqs.plugins.comment")
require("fqs.plugins.nvim-tree")
require("fqs.plugins.lualine")
require("fqs.plugins.telescope")
require("fqs.plugins.nvim-cmp")
require("fqs.plugins.lsp.mason")
require("fqs.plugins.lsp.lspsaga")
require("fqs.plugins.lsp.lspconfig")
require("fqs.plugins.lsp.null-ls")
require("fqs.plugins.autopairs")
require("fqs.plugins.treesitter")
-- require("fqs.plugins.gitsigns")
-- require("fqs.plugins.neoscroll")
-- require("fqs.plugins.barbecue")
require("fqs.plugins.transparent")
-- require("fqs.plugins.tabline")
-- require("fqs.plugins.nvim-colorizer")
-- require("fqs.plugins.indent-blankline")
-- require("fqs.plugins.toggleterm")
-- require("fqs.plugins.bufferline")
